apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pv0001" 
spec:
  capacity:
    storage: "20Gi" 
  accessModes:
    - "ReadWriteMany"
  storageClassName: azure-file-sc
  azureFile:
    secretName: storage-file
    shareName: share-1 
    readOnly: false
