apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "claim1" 
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "20Gi" 
  storageClassName: azure-file-sc 
  volumeName: "pv0001"
