apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "claim2" 
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "20Gi" 
  storageClassName: azure-file-sc 
  volumeName: "pv0002"
